### ISSUE TITLE
Moving to an existing game engine?

### ISSUE THREAD

**Issue by mquinson** [Ferdzz/EvergreenAcres#1]
Hello,
I was wondering whether you considered using an existing game engine such as http://www.solarus-games.org/ to implement this game. I would love to have an open-source HM remake, and I think it'd be faster and easier with such an existing engine.

Thanks for this project, I'm definitely looking forward playing it ;)

**Comment by Ferdzz** [comment]
I'm currently using LibGDX, so I don't have a need to use a different game engine. Plus, that engine looks pretty limited compared to what I can do with freecode like LibGDX.  

I appreciate the interest :) stay tuned for when I finally get back to drawing some more and can make more progress

**Comment by mquinson** [comment]
Hello again, 
I'm not sure I see how solarus is limited here. I don't know that toolbox that well, but it seems like the perfect tooling for a game similar to HM. Plus, that's an open-source project which would certainly accept any contribution if we are missing some features. 
Could you be more specific on the missing features? It seems rather impressive to me: https://www.youtube.com/watch?v=Kup7iDBPBFQ I'd be really interested in your advice here.
NB: I'm actually not affiliated with solarus, I just find it interesting and promising.
